# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    versioning-strategy: "increase"
    schedule:
      interval: "monthly"
    groups:
      dev-deps:
        dependency-type: "development"
      prod-deps:
        dependency-type: "production"
    ignore:
      - dependency-name: "@types/react"
        versions: ["19.x"]
      - dependency-name: "@types/react-dom"
        versions: ["19.x"]
      - dependency-name: "react"
        versions: ["19.x"]
      - dependency-name: "react-dom"
        versions: ["19.x"]
      - dependency-name: "@storybook/addon-essentials"
        versions: ["9.x"]
      - dependency-name: "@storybook/react"
        versions: ["9.x"]
      - dependency-name: "@storybook/react-vite"
        versions: ["9.x"]
      - dependency-name: "storybook"
        versions: ["9.x"]
      - dependency-name: "styled-components"
        versions: ["6.x"]
      - dependency-name: "vite"
        versions: ["7.x"]
