import { faker } from "@faker-js/faker";

import { type DeleteEvent, type PushEvent, type UserEvent } from "./interface";

export function randomDeleteEvent(): DeleteEvent {
  return {
    ...randomUserEventBase(),
    payload: {
      pusher_type: "user",
      ref: faker.git.branch(),
      ref_type: "branch",
    },
    type: "DeleteEvent",
  };
}

export function randomPullRequestEvent() {
  const issue = Number(faker.string.numeric());
  const repo = `${faker.word.noun()}/${faker.word.noun()}`;
  const user = faker.word.noun();
  return {
    ...randomUserEventBase(),
    payload: {
      action: "closed",
      number: issue,
      pull_request: {
        _links: {
          comments: {
            href: `https://api.github.com/repos/${repo}/issues/${issue}/comments`,
          },
          commits: {
            href: `https://api.github.com/repos/${repo}/pulls/${issue}/commits`,
          },
          html: {
            href: `https://github.com/${repo}/pull/${issue}`,
          },
          issue: {
            href: `https://api.github.com/repos/${repo}/issues/${issue}`,
          },
          review_comment: {
            href: `https://api.github.com/repos/${repo}/pulls/comments{/number}`,
          },
          review_comments: {
            href: `https://api.github.com/repos/${repo}/pulls/${issue}/comments`,
          },
          self: {
            href: `https://api.github.com/repos/${repo}/pulls/${issue}`,
          },
          statuses: {
            href: `https://api.github.com/repos/${repo}/statuses/${faker.git.commitSha()}`,
          },
        },
        active_lock_reason: null,
        additions: faker.number.int(),
        assignee: null,
        assignees: [],
        author_association: "CONTRIBUTOR",
        auto_merge: {
          commit_message: faker.git.commitMessage(),
          commit_title: faker.git.commitMessage(),
          enabled_by: {
            avatar_url: faker.image.avatarGitHub(),
            events_url: `https://api.github.com/users/${user}/events{/privacy}`,
            followers_url: `https://api.github.com/users/${user}/followers`,
            following_url: `https://api.github.com/users/${user}/following{/other_user}`,
            gists_url: `https://api.github.com/users/${user}/gists{/gist_id}`,
            gravatar_id: "",
            html_url: `https://github.com/${user}`,
            id: Number(faker.string.numeric(7)),
            login: `${user}`,
            node_id: faker.string.nanoid(),
            organizations_url: `https://api.github.com/users/${user}/orgs`,
            received_events_url: `https://api.github.com/users/${user}/received_events`,
            repos_url: `https://api.github.com/users/${user}/repos`,
            site_admin: faker.datatype.boolean(),
            starred_url: `https://api.github.com/users/${user}/starred{/owner}{/repo}`,
            subscriptions_url: `https://api.github.com/users/${user}/subscriptions`,
            type: "User",
            url: `https://api.github.com/users/${user}`,
            user_view_type: "public",
          },
          merge_method: "squash",
        },
        base: {
          label: "oomol:main",
          ref: "main",
          repo: {
            allow_forking: true,
            archive_url: "https://api.github.com/repos/oomol/oomol-studio-code/{archive_format}{/ref}",
            archived: false,
            assignees_url: "https://api.github.com/repos/oomol/oomol-studio-code/assignees{/user}",
            blobs_url: "https://api.github.com/repos/oomol/oomol-studio-code/git/blobs{/sha}",
            branches_url: "https://api.github.com/repos/oomol/oomol-studio-code/branches{/branch}",
            clone_url: "https://github.com/oomol/oomol-studio-code.git",
            collaborators_url: "https://api.github.com/repos/oomol/oomol-studio-code/collaborators{/collaborator}",
            comments_url: "https://api.github.com/repos/oomol/oomol-studio-code/comments{/number}",
            commits_url: "https://api.github.com/repos/oomol/oomol-studio-code/commits{/sha}",
            compare_url: "https://api.github.com/repos/oomol/oomol-studio-code/compare/{base}...{head}",
            contents_url: "https://api.github.com/repos/oomol/oomol-studio-code/contents/{+path}",
            contributors_url: "https://api.github.com/repos/oomol/oomol-studio-code/contributors",
            created_at: "2024-07-10T02:23:28Z",
            default_branch: "main",
            deployments_url: "https://api.github.com/repos/oomol/oomol-studio-code/deployments",
            description: null,
            disabled: false,
            downloads_url: "https://api.github.com/repos/oomol/oomol-studio-code/downloads",
            events_url: "https://api.github.com/repos/oomol/oomol-studio-code/events",
            fork: false,
            forks: 4,
            forks_count: 4,
            forks_url: "https://api.github.com/repos/oomol/oomol-studio-code/forks",
            full_name: "oomol/oomol-studio-code",
            git_commits_url: "https://api.github.com/repos/oomol/oomol-studio-code/git/commits{/sha}",
            git_refs_url: "https://api.github.com/repos/oomol/oomol-studio-code/git/refs{/sha}",
            git_tags_url: "https://api.github.com/repos/oomol/oomol-studio-code/git/tags{/sha}",
            git_url: "git://github.com/oomol/oomol-studio-code.git",
            has_discussions: false,
            has_downloads: true,
            has_issues: true,
            has_pages: false,
            has_projects: false,
            has_wiki: false,
            homepage: null,
            hooks_url: "https://api.github.com/repos/oomol/oomol-studio-code/hooks",
            html_url: "https://github.com/oomol/oomol-studio-code",
            id: 826589494,
            is_template: false,
            issue_comment_url: "https://api.github.com/repos/oomol/oomol-studio-code/issues/comments{/number}",
            issue_events_url: "https://api.github.com/repos/oomol/oomol-studio-code/issues/events{/number}",
            issues_url: "https://api.github.com/repos/oomol/oomol-studio-code/issues{/number}",
            keys_url: "https://api.github.com/repos/oomol/oomol-studio-code/keys{/key_id}",
            labels_url: "https://api.github.com/repos/oomol/oomol-studio-code/labels{/name}",
            language: "TypeScript",
            languages_url: "https://api.github.com/repos/oomol/oomol-studio-code/languages",
            license: {
              key: "other",
              name: "Other",
              node_id: "MDc6TGljZW5zZTA=",
              spdx_id: "NOASSERTION",
              url: null,
            },
            merges_url: "https://api.github.com/repos/oomol/oomol-studio-code/merges",
            milestones_url: "https://api.github.com/repos/oomol/oomol-studio-code/milestones{/number}",
            mirror_url: null,
            name: "oomol-studio-code",
            node_id: "R_kgDOMUTBNg",
            notifications_url:
              "https://api.github.com/repos/oomol/oomol-studio-code/notifications{?since,all,participating}",
            open_issues: 3,
            open_issues_count: 3,
            owner: {
              avatar_url: "https://avatars.githubusercontent.com/u/95742941?v=4",
              events_url: "https://api.github.com/users/oomol/events{/privacy}",
              followers_url: "https://api.github.com/users/oomol/followers",
              following_url: "https://api.github.com/users/oomol/following{/other_user}",
              gists_url: "https://api.github.com/users/oomol/gists{/gist_id}",
              gravatar_id: "",
              html_url: "https://github.com/oomol",
              id: 95742941,
              login: "oomol",
              node_id: "O_kgDOBbTr3Q",
              organizations_url: "https://api.github.com/users/oomol/orgs",
              received_events_url: "https://api.github.com/users/oomol/received_events",
              repos_url: "https://api.github.com/users/oomol/repos",
              site_admin: false,
              starred_url: "https://api.github.com/users/oomol/starred{/owner}{/repo}",
              subscriptions_url: "https://api.github.com/users/oomol/subscriptions",
              type: "Organization",
              url: "https://api.github.com/users/oomol",
              user_view_type: "public",
            },
            private: true,
            pulls_url: "https://api.github.com/repos/oomol/oomol-studio-code/pulls{/number}",
            pushed_at: "2025-01-27T04:30:12Z",
            releases_url: "https://api.github.com/repos/oomol/oomol-studio-code/releases{/id}",
            size: 39326,
            ssh_url: "git@github.com:oomol/oomol-studio-code.git",
            stargazers_count: 0,
            stargazers_url: "https://api.github.com/repos/oomol/oomol-studio-code/stargazers",
            statuses_url: "https://api.github.com/repos/oomol/oomol-studio-code/statuses/{sha}",
            subscribers_url: "https://api.github.com/repos/oomol/oomol-studio-code/subscribers",
            subscription_url: "https://api.github.com/repos/oomol/oomol-studio-code/subscription",
            svn_url: "https://github.com/oomol/oomol-studio-code",
            tags_url: "https://api.github.com/repos/oomol/oomol-studio-code/tags",
            teams_url: "https://api.github.com/repos/oomol/oomol-studio-code/teams",
            topics: [],
            trees_url: "https://api.github.com/repos/oomol/oomol-studio-code/git/trees{/sha}",
            updated_at: "2025-01-26T14:04:25Z",
            url: "https://api.github.com/repos/oomol/oomol-studio-code",
            visibility: "private",
            watchers: 0,
            watchers_count: 0,
            web_commit_signoff_required: false,
          },
          sha: "5c202fcd99bc124048d9411f3d1dca8240d31692",
          user: {
            avatar_url: "https://avatars.githubusercontent.com/u/95742941?v=4",
            events_url: "https://api.github.com/users/oomol/events{/privacy}",
            followers_url: "https://api.github.com/users/oomol/followers",
            following_url: "https://api.github.com/users/oomol/following{/other_user}",
            gists_url: "https://api.github.com/users/oomol/gists{/gist_id}",
            gravatar_id: "",
            html_url: "https://github.com/oomol",
            id: 95742941,
            login: "oomol",
            node_id: "O_kgDOBbTr3Q",
            organizations_url: "https://api.github.com/users/oomol/orgs",
            received_events_url: "https://api.github.com/users/oomol/received_events",
            repos_url: "https://api.github.com/users/oomol/repos",
            site_admin: false,
            starred_url: "https://api.github.com/users/oomol/starred{/owner}{/repo}",
            subscriptions_url: "https://api.github.com/users/oomol/subscriptions",
            type: "Organization",
            url: "https://api.github.com/users/oomol",
            user_view_type: "public",
          },
        },
        body: "This PR contains the following updates:\n\n| Package | Type | Update | Change |\n|---|---|---|---|\n| [@oomol/studio-core](https://redirect.github.com/oomol/oomol-studio-core) | dependencies | patch | [`0.0.274` -> `0.0.275`](https://renovatebot.com/diffs/npm/@oomol%2fstudio-core/0.0.274/0.0.275) |\n| [@oomol/studio-core](https://redirect.github.com/oomol/oomol-studio-core) | pnpm.overrides | patch | [`0.0.274` -> `0.0.275`](https://renovatebot.com/diffs/npm/@oomol%2fstudio-core/0.0.274/0.0.275) |\n\n---\n\n### Release Notes\n\n<details>\n<summary>oomol/oomol-studio-core (@&#8203;oomol/studio-core)</summary>\n\n### [`v0.0.275`](https://redirect.github.com/oomol/oomol-studio-core/compare/@oomol/studio-core-v0.0.274...@oomol/studio-core-v0.0.275)\n\n[Compare Source](https://redirect.github.com/oomol/oomol-studio-core/compare/@oomol/studio-core-v0.0.274...@oomol/studio-core-v0.0.275)\n\n</details>\n\n---\n\n### Configuration\n\n📅 **Schedule**: Branch creation - At any time (no schedule defined), Automerge - At any time (no schedule defined).\n\n🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.\n\n♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.\n\n🔕 **Ignore**: Close this PR and you won't be reminded about these updates again.\n\n---\n\n - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check this box\n\n---\n\nThis PR has been generated by [Renovate Bot](https://redirect.github.com/renovatebot/renovate).\n<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOS4xMzQuMCIsInVwZGF0ZWRJblZlciI6IjM5LjEzNC4wIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6WyJzdHVkaW8tY29yZSJdfQ==-->\n",
        changed_files: 4,
        closed_at: "2025-01-27T04:30:12Z",
        comments: 0,
        comments_url: "https://api.github.com/repos/oomol/oomol-studio-code/issues/1208/comments",
        commits: 1,
        commits_url: "https://api.github.com/repos/oomol/oomol-studio-code/pulls/1208/commits",
        created_at: "2025-01-27T04:28:22Z",
        deletions: 17,
        diff_url: "https://github.com/oomol/oomol-studio-code/pull/1208.diff",
        draft: false,
        head: {
          label: "oomol:renovate/oomol-studio-core-0.x",
          ref: "renovate/oomol-studio-core-0.x",
          repo: {
            allow_forking: true,
            archive_url: "https://api.github.com/repos/oomol/oomol-studio-code/{archive_format}{/ref}",
            archived: false,
            assignees_url: "https://api.github.com/repos/oomol/oomol-studio-code/assignees{/user}",
            blobs_url: "https://api.github.com/repos/oomol/oomol-studio-code/git/blobs{/sha}",
            branches_url: "https://api.github.com/repos/oomol/oomol-studio-code/branches{/branch}",
            clone_url: "https://github.com/oomol/oomol-studio-code.git",
            collaborators_url: "https://api.github.com/repos/oomol/oomol-studio-code/collaborators{/collaborator}",
            comments_url: "https://api.github.com/repos/oomol/oomol-studio-code/comments{/number}",
            commits_url: "https://api.github.com/repos/oomol/oomol-studio-code/commits{/sha}",
            compare_url: "https://api.github.com/repos/oomol/oomol-studio-code/compare/{base}...{head}",
            contents_url: "https://api.github.com/repos/oomol/oomol-studio-code/contents/{+path}",
            contributors_url: "https://api.github.com/repos/oomol/oomol-studio-code/contributors",
            created_at: "2024-07-10T02:23:28Z",
            default_branch: "main",
            deployments_url: "https://api.github.com/repos/oomol/oomol-studio-code/deployments",
            description: null,
            disabled: false,
            downloads_url: "https://api.github.com/repos/oomol/oomol-studio-code/downloads",
            events_url: "https://api.github.com/repos/oomol/oomol-studio-code/events",
            fork: false,
            forks: 4,
            forks_count: 4,
            forks_url: "https://api.github.com/repos/oomol/oomol-studio-code/forks",
            full_name: "oomol/oomol-studio-code",
            git_commits_url: "https://api.github.com/repos/oomol/oomol-studio-code/git/commits{/sha}",
            git_refs_url: "https://api.github.com/repos/oomol/oomol-studio-code/git/refs{/sha}",
            git_tags_url: "https://api.github.com/repos/oomol/oomol-studio-code/git/tags{/sha}",
            git_url: "git://github.com/oomol/oomol-studio-code.git",
            has_discussions: false,
            has_downloads: true,
            has_issues: true,
            has_pages: false,
            has_projects: false,
            has_wiki: false,
            homepage: null,
            hooks_url: "https://api.github.com/repos/oomol/oomol-studio-code/hooks",
            html_url: "https://github.com/oomol/oomol-studio-code",
            id: 826589494,
            is_template: false,
            issue_comment_url: "https://api.github.com/repos/oomol/oomol-studio-code/issues/comments{/number}",
            issue_events_url: "https://api.github.com/repos/oomol/oomol-studio-code/issues/events{/number}",
            issues_url: "https://api.github.com/repos/oomol/oomol-studio-code/issues{/number}",
            keys_url: "https://api.github.com/repos/oomol/oomol-studio-code/keys{/key_id}",
            labels_url: "https://api.github.com/repos/oomol/oomol-studio-code/labels{/name}",
            language: "TypeScript",
            languages_url: "https://api.github.com/repos/oomol/oomol-studio-code/languages",
            license: {
              key: "other",
              name: "Other",
              node_id: "MDc6TGljZW5zZTA=",
              spdx_id: "NOASSERTION",
              url: null,
            },
            merges_url: "https://api.github.com/repos/oomol/oomol-studio-code/merges",
            milestones_url: "https://api.github.com/repos/oomol/oomol-studio-code/milestones{/number}",
            mirror_url: null,
            name: "oomol-studio-code",
            node_id: "R_kgDOMUTBNg",
            notifications_url:
              "https://api.github.com/repos/oomol/oomol-studio-code/notifications{?since,all,participating}",
            open_issues: 3,
            open_issues_count: 3,
            owner: {
              avatar_url: "https://avatars.githubusercontent.com/u/95742941?v=4",
              events_url: "https://api.github.com/users/oomol/events{/privacy}",
              followers_url: "https://api.github.com/users/oomol/followers",
              following_url: "https://api.github.com/users/oomol/following{/other_user}",
              gists_url: "https://api.github.com/users/oomol/gists{/gist_id}",
              gravatar_id: "",
              html_url: "https://github.com/oomol",
              id: 95742941,
              login: "oomol",
              node_id: "O_kgDOBbTr3Q",
              organizations_url: "https://api.github.com/users/oomol/orgs",
              received_events_url: "https://api.github.com/users/oomol/received_events",
              repos_url: "https://api.github.com/users/oomol/repos",
              site_admin: false,
              starred_url: "https://api.github.com/users/oomol/starred{/owner}{/repo}",
              subscriptions_url: "https://api.github.com/users/oomol/subscriptions",
              type: "Organization",
              url: "https://api.github.com/users/oomol",
              user_view_type: "public",
            },
            private: true,
            pulls_url: "https://api.github.com/repos/oomol/oomol-studio-code/pulls{/number}",
            pushed_at: "2025-01-27T04:30:12Z",
            releases_url: "https://api.github.com/repos/oomol/oomol-studio-code/releases{/id}",
            size: 39326,
            ssh_url: "git@github.com:oomol/oomol-studio-code.git",
            stargazers_count: 0,
            stargazers_url: "https://api.github.com/repos/oomol/oomol-studio-code/stargazers",
            statuses_url: "https://api.github.com/repos/oomol/oomol-studio-code/statuses/{sha}",
            subscribers_url: "https://api.github.com/repos/oomol/oomol-studio-code/subscribers",
            subscription_url: "https://api.github.com/repos/oomol/oomol-studio-code/subscription",
            svn_url: "https://github.com/oomol/oomol-studio-code",
            tags_url: "https://api.github.com/repos/oomol/oomol-studio-code/tags",
            teams_url: "https://api.github.com/repos/oomol/oomol-studio-code/teams",
            topics: [],
            trees_url: "https://api.github.com/repos/oomol/oomol-studio-code/git/trees{/sha}",
            updated_at: "2025-01-26T14:04:25Z",
            url: "https://api.github.com/repos/oomol/oomol-studio-code",
            visibility: "private",
            watchers: 0,
            watchers_count: 0,
            web_commit_signoff_required: false,
          },
          sha: "e1631c49338104d6e063bbed961ab74ab896a44e",
          user: {
            avatar_url: "https://avatars.githubusercontent.com/u/95742941?v=4",
            events_url: "https://api.github.com/users/oomol/events{/privacy}",
            followers_url: "https://api.github.com/users/oomol/followers",
            following_url: "https://api.github.com/users/oomol/following{/other_user}",
            gists_url: "https://api.github.com/users/oomol/gists{/gist_id}",
            gravatar_id: "",
            html_url: "https://github.com/oomol",
            id: 95742941,
            login: "oomol",
            node_id: "O_kgDOBbTr3Q",
            organizations_url: "https://api.github.com/users/oomol/orgs",
            received_events_url: "https://api.github.com/users/oomol/received_events",
            repos_url: "https://api.github.com/users/oomol/repos",
            site_admin: false,
            starred_url: "https://api.github.com/users/oomol/starred{/owner}{/repo}",
            subscriptions_url: "https://api.github.com/users/oomol/subscriptions",
            type: "Organization",
            url: "https://api.github.com/users/oomol",
            user_view_type: "public",
          },
        },
        html_url: "https://github.com/oomol/oomol-studio-code/pull/1208",
        id: Number(faker.string.numeric(10)),
        issue_url: "https://api.github.com/repos/oomol/oomol-studio-code/issues/1208",
        labels: [
          {
            color: "ededed",
            default: false,
            description: null,
            id: Number(faker.string.numeric(10)),
            name: "studio-core",
            node_id: "LA_kwDOMUTBNs8AAAAB1uO3OQ",
            url: "https://api.github.com/repos/oomol/oomol-studio-code/labels/studio-core",
          },
        ],
        locked: false,
        maintainer_can_modify: false,
        merge_commit_sha: "ee9ee640ec78c84ed565a06dad0ccf3f11e183a2",
        mergeable: null,
        mergeable_state: "unknown",
        merged: true,
        merged_at: "2025-01-27T04:30:12Z",
        merged_by: {
          avatar_url: "https://avatars.githubusercontent.com/u/6882794?v=4",
          events_url: "https://api.github.com/users/crimx/events{/privacy}",
          followers_url: "https://api.github.com/users/crimx/followers",
          following_url: "https://api.github.com/users/crimx/following{/other_user}",
          gists_url: "https://api.github.com/users/crimx/gists{/gist_id}",
          gravatar_id: "",
          html_url: "https://github.com/crimx",
          id: 6882794,
          login: "crimx",
          node_id: "MDQ6VXNlcjY4ODI3OTQ=",
          organizations_url: "https://api.github.com/users/crimx/orgs",
          received_events_url: "https://api.github.com/users/crimx/received_events",
          repos_url: "https://api.github.com/users/crimx/repos",
          site_admin: false,
          starred_url: "https://api.github.com/users/crimx/starred{/owner}{/repo}",
          subscriptions_url: "https://api.github.com/users/crimx/subscriptions",
          type: "User",
          url: "https://api.github.com/users/crimx",
          user_view_type: "public",
        },
        milestone: null,
        node_id: "PR_kwDOMUTBNs6JCJax",
        number: 1208,
        patch_url: "https://github.com/oomol/oomol-studio-code/pull/1208.patch",
        rebaseable: null,
        requested_reviewers: [
          {
            avatar_url: "https://avatars.githubusercontent.com/u/8299540?v=4",
            events_url: "https://api.github.com/users/l1shen/events{/privacy}",
            followers_url: "https://api.github.com/users/l1shen/followers",
            following_url: "https://api.github.com/users/l1shen/following{/other_user}",
            gists_url: "https://api.github.com/users/l1shen/gists{/gist_id}",
            gravatar_id: "",
            html_url: "https://github.com/l1shen",
            id: 8299540,
            login: "l1shen",
            node_id: "MDQ6VXNlcjgyOTk1NDA=",
            organizations_url: "https://api.github.com/users/l1shen/orgs",
            received_events_url: "https://api.github.com/users/l1shen/received_events",
            repos_url: "https://api.github.com/users/l1shen/repos",
            site_admin: false,
            starred_url: "https://api.github.com/users/l1shen/starred{/owner}{/repo}",
            subscriptions_url: "https://api.github.com/users/l1shen/subscriptions",
            type: "User",
            url: "https://api.github.com/users/l1shen",
            user_view_type: "public",
          },
        ],
        requested_teams: [],
        review_comment_url: "https://api.github.com/repos/oomol/oomol-studio-code/pulls/comments{/number}",
        review_comments: 0,
        review_comments_url: "https://api.github.com/repos/oomol/oomol-studio-code/pulls/1208/comments",
        state: "closed",
        statuses_url:
          "https://api.github.com/repos/oomol/oomol-studio-code/statuses/e1631c49338104d6e063bbed961ab74ab896a44e",
        title: "fix(deps): update dependency @oomol/studio-core to v0.0.275",
        updated_at: "2025-01-27T04:30:13Z",
        url: "https://api.github.com/repos/oomol/oomol-studio-code/pulls/1208",
        user: {
          avatar_url: "https://avatars.githubusercontent.com/u/122335590?v=4",
          events_url: "https://api.github.com/users/oomol-bot/events{/privacy}",
          followers_url: "https://api.github.com/users/oomol-bot/followers",
          following_url: "https://api.github.com/users/oomol-bot/following{/other_user}",
          gists_url: "https://api.github.com/users/oomol-bot/gists{/gist_id}",
          gravatar_id: "",
          html_url: "https://github.com/oomol-bot",
          id: 122335590,
          login: "oomol-bot",
          node_id: "U_kgDOB0qxZg",
          organizations_url: "https://api.github.com/users/oomol-bot/orgs",
          received_events_url: "https://api.github.com/users/oomol-bot/received_events",
          repos_url: "https://api.github.com/users/oomol-bot/repos",
          site_admin: false,
          starred_url: "https://api.github.com/users/oomol-bot/starred{/owner}{/repo}",
          subscriptions_url: "https://api.github.com/users/oomol-bot/subscriptions",
          type: "User",
          url: "https://api.github.com/users/oomol-bot",
          user_view_type: "public",
        },
      },
    },
    type: "PullRequestEvent",
  };
}

export function randomPushEvent(): PushEvent {
  const commits = faker.helpers.uniqueArray(randomCommit, faker.number.int({ max: 5, min: 1 }));
  return {
    ...randomUserEventBase(),
    payload: {
      before: faker.git.commitSha(),
      commits,
      distinct_size: commits.reduce((acc, commit) => acc + (commit.distinct ? 1 : 0), 0),
      head: faker.git.commitSha(),
      push_id: Number(faker.string.numeric(11)),
      ref: "refs/heads/main",
      repository_id: Number(faker.string.numeric(9)),
      size: commits.length,
    },
    type: "PushEvent",
  };
}

function randomActor(): UserEvent["actor"] {
  const user = faker.word.noun();
  return {
    avatar_url: faker.image.avatarGitHub(),
    display_login: user,
    gravatar_id: "",
    id: Number(faker.string.numeric(7)),
    login: user,
    url: `https://api.github.com/users/${user}`,
  };
}

function randomCommit(): PushEvent["payload"]["commits"][number] {
  const sha = faker.git.commitSha();
  return {
    author: {
      email: faker.internet.email(),
      name: faker.word.noun(),
    },
    distinct: true,
    message: faker.git.commitMessage(),
    sha,
    url: `https://api.github.com/repos/${faker.word.noun()}/${faker.word.noun()}/commits/${sha}`,
  };
}

function randomOrg(): UserEvent["org"] {
  const name = faker.word.noun();
  return {
    avatar_url: faker.image.avatarGitHub(),
    gravatar_id: "",
    id: Number(faker.string.numeric(9)),
    login: name,
    url: `https://api.github.com/orgs/${name}`,
  };
}

function randomRepo(): UserEvent["repo"] {
  const name = `${faker.lorem.word()}/${faker.lorem.word()}`;
  return {
    id: Number(faker.string.numeric(9)),
    name,
    url: `https://api.github.com/repos/${name}`,
  };
}

function randomUserEventBase(): Omit<UserEvent, "payload" | "type"> {
  return {
    actor: randomActor(),
    created_at: faker.date.past().toISOString(),
    id: faker.string.numeric(11),
    org: randomOrg(),
    public: faker.datatype.boolean(),
    repo: randomRepo(),
  };
}
